name: Test

on: pull_request

jobs:
  test:
    if: github.event.pull_request.draft == false

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: yarn
        
    - name: Yarn
      run: yarn

    - name: Lint
      run: yarn lint

    - name: Test unit
      run: yarn test:unit

    - name: Build
      run: yarn build
